# Generated by Django 5.2.5 on 2025-09-28 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.CharField(max_length=60)),
                ('via', models.CharField(blank=True, max_length=40)),
                ('indicaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=160)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro/ND')], default='O', max_length=1)),
                ('alergias', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HoraProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('dia_semana', models.IntegerField(blank=True, choices=[(0, 'Lun'), (1, 'Mar'), (2, 'Mié'), (3, 'Jue'), (4, 'Vie'), (5, 'Sáb'), (6, 'Dom')], null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas', to='landing.ordenmedicamento')),
            ],
            options={
                'ordering': ['hora'],
            },
        ),
        migrations.AddField(
            model_name='ordenmedicamento',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landing.producto'),
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('inicio', models.DateField()),
                ('fin', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas', to='landing.residente')),
            ],
        ),
        migrations.AddField(
            model_name='ordenmedicamento',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='landing.receta'),
        ),
        migrations.CreateModel(
            name='Administracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programada_para', models.DateTimeField()),
                ('registrada_en', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('DADA', 'Administrada'), ('OMITIDA', 'Omitida'), ('RECHAZADA', 'Rechazada')], max_length=12)),
                ('cantidad_administrada', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('realizada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administraciones', to='landing.ordenmedicamento')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landing.residente')),
            ],
            options={
                'indexes': [models.Index(fields=['programada_para', 'residente'], name='landing_adm_program_06c133_idx')],
                'unique_together': {('orden', 'residente', 'programada_para')},
            },
        ),
    ]
