# Generated by Django 5.2.5 on 2025-09-28 23:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='administracion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='producto',
            name='forma',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='producto',
            name='potencia',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='administracion',
            name='cantidad_administrada',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='administracion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('DADA', 'Administrada'), ('OMITIDA', 'Omitida'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=12),
        ),
        migrations.AlterField(
            model_name='administracion',
            name='realizada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receta',
            name='medico',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
