# Generated by Django 5.2.5 on 2025-10-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_alter_administracion_unique_together_producto_forma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmedicamento',
            name='stock_asignado',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordenmedicamento',
            name='stock_critico',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
