# Generated by Django 5.2.5 on 2025-10-03 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_ordenmedicamento_stock_asignado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administracion',
            name='residente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.residente'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='residente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='landing.residente'),
        ),
    ]
