# Generated by Django 5.2.7 on 2025-10-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_alter_administracion_residente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmedicamento',
            name='alerta_enviada',
            field=models.BooleanField(default=False),
        ),
    ]
