# Generated by Django 5.2.7 on 2025-10-21 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_ordenmedicamento_alerta_enviada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('solo_asignados', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cuidadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to=settings.AUTH_USER_MODEL)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='landing.residente')),
            ],
            options={
                'indexes': [models.Index(fields=['fecha', 'cuidadora'], name='landing_asi_fecha_2235c8_idx'), models.Index(fields=['fecha', 'residente'], name='landing_asi_fecha_99b1ec_idx')],
                'unique_together': {('fecha', 'residente')},
            },
        ),
    ]
