# Generated by Django 5.2.7 on 2025-10-21 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_diaasignacion_asignacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diaasignacion',
            name='cuidadoras',
            field=models.ManyToManyField(blank=True, related_name='dias_asignacion_cuidadoras', to=settings.AUTH_USER_MODEL),
        ),
    ]
