# Generated by Django 5.2.7 on 2025-11-06 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_diaasignacion_cuidadoras'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receta',
            options={'ordering': ['-numero', '-creada_en']},
        ),
        migrations.AddField(
            model_name='receta',
            name='numero',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Número secuencial por residente'),
        ),
        migrations.AddConstraint(
            model_name='receta',
            constraint=models.UniqueConstraint(fields=('residente', 'numero'), name='uniq_receta_por_residente'),
        ),
    ]
